import type { CoverAsset } from "@/lib/types";

export interface InspirationItem
  extends Pick<
    CoverAsset,
    | "topic"
    | "platformId"
    | "styleId"
    | "title"
    | "subtitle"
    | "badge"
    | "mode"
    | "quality"
  > {
  id: string;
  author: string;
}

export const INSPIRATIONS: InspirationItem[] = [
  {
    id: "ins-1",
    author: "阿年笔记",
    topic: "小红书封面点击率翻倍",
    platformId: "xiaohongshu",
    styleId: "knowledge",
    title: "姐妹们，这个封面公式我真的会反复看",
    subtitle: "收藏这一篇，封面不再靠感觉",
    badge: "干货收藏",
    mode: "text",
    quality: "hd",
  },
  {
    id: "ins-2",
    author: "夜航剪辑",
    topic: "短视频前3秒钩子",
    platformId: "shortvideo",
    styleId: "poster",
    title: "停！这个钩子你还在用旧方法吗",
    subtitle: "看完这支就够了 · 短视频封面",
    badge: "别划走",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-3",
    author: "慢茶生活",
    topic: "周末在家做一杯桂花乌龙",
    platformId: "xiaohongshu",
    styleId: "lifestyle",
    title: "普通人也能立刻用上的居家茶仪式",
    subtitle: "收藏这一篇，周末不再靠感觉",
    badge: "今日必看",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-4",
    author: "测评局",
    topic: "三款无线麦真实对比",
    platformId: "thumbnail",
    styleId: "review",
    title: "无线麦翻车 vs 正确示范",
    subtitle: "高对比点击公式 · 缩略图",
    badge: "对比局",
    mode: "text",
    quality: "hd",
  },
  {
    id: "ins-5",
    author: "增长手记",
    topic: "公众号标题与头图配对",
    platformId: "wechat",
    styleId: "business",
    title: "头图配对：一份可直接落地的实操清单",
    subtitle: "读完即可执行 · 附可复用结构",
    badge: "可落地",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-6",
    author: "极夜Studio",
    topic: "AI 工具一周实战复盘",
    platformId: "thumbnail",
    styleId: "nighttech",
    title: "投入1小时，复盘效果差10倍",
    subtitle: "高对比点击公式 · 缩略图",
    badge: "数据说话",
    mode: "text",
    quality: "hd",
  },
  {
    id: "ins-7",
    author: "职场说明书",
    topic: "新人一周上手的周报模板",
    platformId: "wechat",
    styleId: "knowledge",
    title: "周报模板完整路径：从入门到第一次出成果",
    subtitle: "读完即可执行 · 附可复用结构",
    badge: "深度拆解",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-8",
    author: "种草研究所",
    topic: "通勤包到底值不值",
    platformId: "xiaohongshu",
    styleId: "review",
    title: "我的通勤包避雷指南，看完少走三年弯路",
    subtitle: "收藏这一篇，种草不再靠感觉",
    badge: "亲测有效",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-9",
    author: "竖屏实验室",
    topic: "一条视频如何做出封面悬念",
    platformId: "shortvideo",
    styleId: "nighttech",
    title: "3秒看懂封面悬念，看完立刻能上手",
    subtitle: "看完这支就够了 · 短视频封面",
    badge: "3秒钩子",
    mode: "text",
    quality: "hd",
  },
  {
    id: "ins-10",
    author: "字大如斗",
    topic: "把一句卖点写到最大",
    platformId: "shortvideo",
    styleId: "poster",
    title: "90%的人不知道：大字报其实可以这样",
    subtitle: "看完这支就够了 · 短视频封面",
    badge: "停下来看",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-11",
    author: "白纸商务",
    topic: "咨询顾问如何做专业头图",
    platformId: "wechat",
    styleId: "business",
    title: "写给认真做内容的人：专业头图避坑与提效",
    subtitle: "读完即可执行 · 附可复用结构",
    badge: "实操清单",
    mode: "text",
    quality: "standard",
  },
  {
    id: "ins-12",
    author: "晨间生活",
    topic: "五分钟晨间拉伸",
    platformId: "xiaohongshu",
    styleId: "lifestyle",
    title: "做完这件事，才懂晨间拉伸为什么一直被转发",
    subtitle: "收藏这一篇，身体状态不再靠感觉",
    badge: "今日必看",
    mode: "text",
    quality: "standard",
  },
];
